export const FRANCY = {
  name: 'Francy Molano Nails Studio',
  shortName: 'Francy Molano',
  whatsapp: '573106920842',
  phoneDisplay: '310 692 0842',
  phoneE164: '+573106920842',
  instagram: 'francymolano_nails',
  tiktok: 'francymolano_nails',
  address: 'Calle 25 #21-40 Paipa',
  street: 'Calle 25 #21-40',
  city: 'Paipa',
  region: 'Boyacá',
  postalCode: '150410',
  country: 'CO',
  geo: { lat: 5.7803, lng: -73.1156 },
  priceRange: '$$',
  currency: 'COP',
  closing: '18:00',
  url: 'https://felipeleon.example.com/demos/francy',
  seoTitle: 'Uñas Semipermanentes en Paipa | Francy Molano',
  seoDescription:
    'Estudio de uñas en Paipa, Boyacá. Manicure, semipermanente, acrílicas, pedicure spa, cejas y pestañas con producto profesional. Agenda tu cita por WhatsApp.',
  hours: [
    {
      label: 'Lunes a viernes',
      value: '9:00 am – 6:00 pm',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    {
      label: 'Sábado',
      value: '9:00 am – 6:00 pm',
      days: ['Saturday'],
      opens: '09:00',
      closes: '18:00',
    },
    {
      label: 'Domingo y festivos',
      value: 'Solo con cita previa',
      days: [],
      opens: '',
      closes: '',
    },
  ],
} as const;
